# Generated by Django 3.2.24 on 2025-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='images/Menu Items/default.jpg', upload_to='images/Menu Items'),
        ),
    ]
