# Generated by Django 3.2.24 on 2025-02-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0002_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('image', models.ImageField(default='images/Specials/default.jpg', upload_to='images/Specials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
