# Generated by Django 3.2.24 on 2025-03-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0003_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('event_description', models.TextField()),
                ('features', models.TextField(help_text='Please insert each feature on a new line')),
            ],
        ),
    ]
