# Generated by Django 3.2.24 on 2025-03-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
