# Generated by Django 3.2.24 on 2025-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0007_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('testimony', models.TextField()),
                ('image', models.ImageField(default='images/Testimonials/default.jpg', upload_to='images/Testimonials')),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
