# Generated by Django 3.2.24 on 2025-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0008_auto_20250301_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/Gallery/default.jpg', upload_to='images/Gallery')),
            ],
        ),
    ]
