# Generated by Django 3.2.24 on 2025-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
