# Generated by Django 3.2.24 on 2025-03-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0011_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='poa',
            new_name='position',
        ),
    ]
