# Generated by Django 3.2.24 on 2025-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0012_rename_poa_staff_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='images/Staff/default.jpg', upload_to='images/Staff'),
        ),
    ]
