# Generated by Django 3.2.24 on 2025-04-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0013_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
