# Generated by Django 3.2.24 on 2025-04-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0014_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Approving_staff',
            field=models.CharField(default='Lead supervisor', max_length=100),
        ),
    ]
