# Generated by Django 3.2.24 on 2025-04-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neb', '0015_table_approving_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Approving_staff',
            new_name='approving_staff',
        ),
    ]
